FROM centos:latest
LABEL maintainer="Pavlo Lucik pavel.lucik@gmail.com"
RUN yum -y install nginx
COPY index_centos.html /usr/share/nginx/html/index.html
ENTRYPOINT ["/usr/sbin/nginx","-g","daemon off;"]
EXPOSE 80
