FROM debian:stretch

RUN apt-get update && \
    apt-get -y install nginx && \
    apt-get -y install curl 

VOLUME ["/etc/nginx/sites-enabled", "/etc/nginx/certs", "/etc/nginx/conf.d", "/var/log/nginx", "/var/www/html"]

WORKDIR /etc/nginx

EXPOSE 80
EXPOSE 443

COPY start.sh ./

ENTRYPOINT ["./start.sh"]

