FROM ubuntu:18.04
MAINTAINER Max Parasich <parasitchmax@gmail.com>
RUN apt-get update && apt install -y cowsay && ln -s /usr/games/cowsay /usr/bin/cowsay
ENTRYPOINT ["cowsay"]
CMD ["You did it. And what dit it cost ?"]
