FROM centos
LABEL maintainer=“yd77work@gmail.com“
RUN yum install -y httpd && \
yum clean all 
RUN echo "my httpd container" > /var/www/html/index.html
# ADD/COPY index.html /var/www/html/
EXPOSE 80
ENTRYPOINT ["httpd"]
CMD ["-DFOREGROUND"]