
FROM ubuntu:latest

LABEL maintainer=“DevDevchenko“

RUN apt update
RUN apt install -y curl gnupg2 ca-certificates lsb-release

RUN echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" \
    | tee /etc/apt/sources.list.d/nginx.list

RUN curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -

RUN apt update
RUN apt install -y nginx

COPY index.html /usr/share/nginx/html/index.html

CMD ["nginx", "-g daemon off;"]

EXPOSE 80


