FROM maven:3.3-jdk-8 as builder
COPY . /build/
WORKDIR /build
RUN mvn clean install

FROM java:8
ADD demoapp.jar .
EXPOSE 8080
ENTRYPOINT ["java", "-jar","demoapp.jar"]

#FROM alpine:latest  
#RUN apk --no-cache add ca-certificates
#WORKDIR /root/
#COPY --from=0 /go/src/github.com/alexellis/href-counter/app .
#CMD ["./app"]  